export const BOOKS_DI_CONSTANTS = {
  BOOKS_REPOSITORY: Symbol('BOOKS_REPOSITORY'),
  GET_BOOK_WITH_REVIEWS_CASE: Symbol('GET_BOOK_WITH_REVIEWS_CASE'),
  GET_PAGINATED_BOOKS_BY_SECTION_CASE: Symbol('GET_PAGINATED_BOOKS_BY_SECTION_CASE'),
  GET_RECOMMENDED_BOOKS_CASE: Symbol('GET_RECOMMENDED_BOOKS_CASE'),
  GET_SECTIONS_WITH_BOOKS_CASE: Symbol('GET_SECTIONS_WITH_BOOKS_CASE'),
};
